variables:
- group: GitHub Token
- group: VS Marketplace Token
trigger:
  branches:
    include:
    - master
    - release/v*
    - refs/tags/v*
pr:
  branches:
    include:
    - master
    - release/v*
pool:
  vmImage: 'ubuntu-16.04'
steps:
- powershell: 'Get-ChildItem Env:'
  displayName: 'Get-ChildItem Env:'
- task: PowerShell@2
  displayName: 'NPM Install'
  inputs:
    targetType: 'inline'
    script: 'npm install'
- task: PowerShell@2
  displayName: 'NPM Build'
  inputs:
    targetType: 'inline'
    script: 'npm run prod:full'
  env:
    GITHUBTOKEN: $(GitHubToken)
    VSMARKETPLACETOKEN: $(VsMarketplaceToken)