pool:
  vmImage: ubuntu-16.04

trigger:
  branches:
    include:
      - master
      - release/v*
      - refs/tags/v*
pr:
  branches:
    include:
      - master
      - release/v*

variables:
  - group: GitHub Token
  - group: VS Marketplace Token


steps:
- checkout: self
  persistCredentials: true
  clean: true

- powershell: 'Get-ChildItem Env:'
  displayName: 'Get-ChildItem Env:'

- task: PowerShell@2
  displayName: NPM Build
  inputs: null
  targetType: inline
  script: 'npm run prod:full'
  env:
    GITHUBTOKEN: $(GitHubToken)
    VSMARKETPLACETOKEN: $(VsMarketplaceToken)

- task: GitHubRelease@0
  inputs:
    gitHubConnection: null
    repositoryName: $(Build.Repository.Name)
    action: create
    target: $(Build.SourceVersion)
    tagSource: auto
    title: Azure Bake ADO Tools Extension
    assets: $(Build.ArtifactStagingDirectory)/*
    assetUploadMode: delete
    release: false
    isDraft: $(DraftRelease)