variables:
- group: GitHub Token
- group: VS Marketplace Token
trigger:
  branches:
    include:
    - master
    - release/v*
    - refs/tags/v*
pr:
  branches:
    include:
    - master
    - release/v*
pool:
  vmImage: 'ubuntu-16.04'
steps:
- powershell: 'Get-ChildItem Env:'
  displayName: 'Get-ChildItem Env:'
- task: PowerShell@2
  displayName: 'NPM Build'
  inputs:
    targetType: filePath
    filePath: ./npm run prod:full
    arguments: '-Target $(Target) -Configuration $(Configuration) -Verbosity $(Verbosity)'
  env:
    GITHUB_TOKEN: $(GitHubToken)
    VS_MARKETPLACE_TOKEN: $(VsMarketplaceToken)